### ISSUE TITLE
Succinct Definition

### ISSUE THREAD

**Issue by chelseakomlo** [mallory/e2ee#6]
A succinct definition for end-to-end security can describe the security of the system by the probability of an adversary's success in breaking the system. Example snippet: 

The adversary successfully subverts an end-to-end encrypted system if it can succeed in either of the following: 1) the adversary can produce the participant's local state (meaning the adversary has learned the contents of participant's messages), or 2) the states of conversation participants do not match (meaning that the adversary has influenced their communication in some way). To prevent the adversary from trivially winning, we do not allow the adversary to compromise the participants' local state.

We can say that a system is end-to-end secure if the adversary has negligible probability of success in either of these two scenarios. 

Work-in-progress citation here: https://github.com/chelseakomlo/e2ee/blob/master/e2ee_definition.pdf

**Comment by mallory** [comment]
Added this in the last version.
